# Generated by Django 5.0.4 on 2024-04-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название стола')),
            ],
        ),
        migrations.CreateModel(
            name='TableFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название стола')),
                ('Description', models.TextField(null=True, verbose_name='Описание')),
                ('Characteristics', models.TextField(verbose_name='Характеристики')),
                ('Price', models.FloatField(verbose_name='Цена')),
                ('Image', models.ImageField(null=True, upload_to='TableSite/static/mainsite/img', verbose_name='Изображение стола')),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.material', verbose_name='Материал')),
            ],
        ),
    ]
