# Generated by Django 5.0.4 on 2024-04-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='tablefurniture',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
    ]
