# Generated by Django 5.0.4 on 2024-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название материала'),
        ),
    ]
