# Generated by Django 5.0.4 on 2024-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_tablefurniture_depth_tablefurniture_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefurniture',
            name='Depth',
            field=models.FloatField(default=0, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='tablefurniture',
            name='Height',
            field=models.FloatField(default=0, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='tablefurniture',
            name='Width',
            field=models.FloatField(default=0, verbose_name='Ширина'),
        ),
    ]
