# Generated by Django 5.0.4 on 2024-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_tablefurniture_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefurniture',
            name='In_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
